version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: litrocerto_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - litrocerto
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  nginx:
    image: nginx:alpine
    container_name: litrocerto_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - litrocerto
    depends_on:
      - app

  db:
    image: postgis/postgis:16-3.4
    container_name: litrocerto_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-litrocerto}
      POSTGRES_USER: ${DB_USERNAME:-litrocerto}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - litrocerto

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: litrocerto_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-litrocerto}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-secret}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - litrocerto

  redis:
    image: redis:7-alpine
    container_name: litrocerto_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - litrocerto

networks:
  litrocerto:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
